### ISSUE TITLE
Pypi version (2.5) out of date

### ISSUE THREAD

**Issue by droher** [panzarino/mlbgame#137]
It looks like the API has introduced breaking changes since the last time mlbgame was updated on PyPi/the latest release (2.5.0 on 4/16/18). `mlbgame.events('2019_08_14_balmlb_nyamlb_1')` will work without a problem when using `master`, but 2.5.0 will fail with this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/mlbgame/__init__.py", line 227, in game_events
    data = mlbgame.events.game_events(game_id)
  File "/usr/local/lib/python3.7/site-packages/mlbgame/events.py", line 48, in game_events
    'bottom': __inning_info(x, 'bottom')
  File "/usr/local/lib/python3.7/site-packages/mlbgame/events.py", line 17, in __inning_info
    half = inning.findall(part)[0]
IndexError: list index out of range
```

In the meantime users can get around this by installing directly from github: `pip3 install git+https://github.com/panzarino/mlbgame.git`

Thank you for all of your hard work on the project!

**Comment by ByronBecker** [comment]
Likewise, one can install that specific version in pipenv like so -> `pipenv install mlbgame~=2.5.0`
