### ISSUE TITLE
Calling BatterStats on game 2017_04_01_pitmlb_tormlb_1 causes UnicodeEncodeError

### ISSUE THREAD

**Issue by zacc** [panzarino/mlbgame#46]
The accented character appears to be in the name of batter Elias Diaz.

Could this be handled properly?

```
Traceback (most recent call last):
<snip>
  File "/home/yyy/.virtualenvs/xxx/local/lib/python2.7/site-packages/mlbgame/__init__.py", line 234, in player_stats
    obj = mlbgame.stats.BatterStats(x)
  File "/home/yyy/.virtualenvs/xxx/local/lib/python2.7/site-packages/mlbgame/object.py", line 25, in __init__
    setattr(self, x, str(data[x]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 1: ordinal not in range(128)
```

**Comment by panzarino** [comment]
I'll see what I can do. As far as I know, I think the system should just keep it in unicode in that case and I am not sure why it is not.
