### ISSUE TITLE
Rain delay to start game causes KeyError: 'home'

### ISSUE THREAD

**Issue by trevor-viljoen** [panzarino/mlbgame#62]
Sample linescore:
```
<linescore away_team_runs="0" home_team_runs="0" away_team_hits="0" home_team_hits="0" away_team_errors="0" home_team_errors="0" note="(rain)  with 0 out in the top of the 1st and a 0-0 count on George Springer.">
  <inning_line_score away="" inning="1"/>
</linescore>
```

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/local/lib/python2.7/site-packages/mlbgame/__init__.py", line 190, in box_score
    data = mlbgame.game.box_score(game_id)
  File "/usr/local/lib/python2.7/site-packages/mlbgame/game.py", line 240, in box_score
    home = x.attrib['home']
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'home'
```

I'm not sure how we want to handle this one. Perhaps add the `note` attribute and wrap some `try/except` blocks around the `home` and `note` variable evaluations?

**Comment by cggarvey** [comment]
I think that makes sense. Defaulting to 0 probably makes sense (although technically it should be NULL/None until the inning begins). Something like this should work.

```python

home = 0
away = 0

with contextlib.suppress(KeyError):
    # home/away attributes may not exist during rain delays 
    home = x.attrib['home']
    away = x.attrib['away']
```

**Comment by msroth** [comment]
I have experienced the same error with a suspended game (2018_05_15_nyamlb_wasmlb_1).  I will make the edit suggested by cggarvey until a fix is in place.
